version: '2'

services:

  go-api-db:
    image: postgres
    container_name: go-api-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kofkuiper
      POSTGRES_PASSWORD: p@assword
      POSTGRES_DB: db-uat