app:
  port: 3333

db:
  driver: "postgres"
  host: "127.0.0.1"
  port: 5432
  username: kofkuiper
  password: p@assword
  database: db-uat

jwt:
  secret: "abcdef"
  timeout: "24h"

chain:
  id: 16888
  rpc: "https://testnet-rpc.ivarex.com"
  blockExplorer: "https://testnet-scan.ivarscan.com"
